/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerProduto;
import Controller.ControllerVendasProdutos;
import Model.ModelProdutos;
import Model.ModelSessaoUsuario;
import Model.ModelVendasProdutos;
import controller.ControllerVenda;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelVenda;
import util.BLDatas;
import util.BLMascaras;

/**
 *
 * @author Marcio Araujo
 */
public class ViewPdv extends javax.swing.JFrame {
    
    ControllerProduto controllerProdutos = new ControllerProduto();
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ModelVenda modelVendas = new ModelVenda();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ControllerVenda controllerVenda = new ControllerVenda();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutoses = new ArrayList<>();
    BLDatas blDatas = new BLDatas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    int quantidade;
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    private  ViewPagamentoPdv viewPagamentoPdv;
    BLMascaras blMascara = new BLMascaras();


    
    /**
     * Creates new form ViewPdv
     */
    public ViewPdv() {
        initComponents();
        setLocationRelativeTo(null);
        quantidade = 1;
        setarOperador();
        
        limparTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPdvVendas = new javax.swing.JTable();
        txtCodPdvProdutos = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtValorBruto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblCaixa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();
        mExcluir = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mQuandidade = new javax.swing.JMenuItem();
        mFinalizarVenda = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PDV ");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        tblPdvVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item:", "Codigo:", "Nome:", "Quandidade:", "Valor Uni:", "Valor Total:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPdvVendas);
        if (tblPdvVendas.getColumnModel().getColumnCount() > 0) {
            tblPdvVendas.getColumnModel().getColumn(0).setMinWidth(40);
            tblPdvVendas.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblPdvVendas.getColumnModel().getColumn(0).setMaxWidth(40);
            tblPdvVendas.getColumnModel().getColumn(1).setMinWidth(70);
            tblPdvVendas.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblPdvVendas.getColumnModel().getColumn(1).setMaxWidth(70);
            tblPdvVendas.getColumnModel().getColumn(3).setMinWidth(80);
            tblPdvVendas.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblPdvVendas.getColumnModel().getColumn(3).setMaxWidth(80);
            tblPdvVendas.getColumnModel().getColumn(4).setMinWidth(70);
            tblPdvVendas.getColumnModel().getColumn(4).setPreferredWidth(70);
            tblPdvVendas.getColumnModel().getColumn(4).setMaxWidth(70);
            tblPdvVendas.getColumnModel().getColumn(5).setMinWidth(70);
            tblPdvVendas.getColumnModel().getColumn(5).setPreferredWidth(70);
            tblPdvVendas.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        txtCodPdvProdutos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCodPdvProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodPdvProdutosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodPdvProdutos)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtCodPdvProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valor Bruto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Comandos");

        jLabel9.setText("Sair = F6");

        jLabel10.setText("Quantidade =  F3");

        jLabel11.setText("Finalizar Venda =  F4");

        jLabel12.setText("Pesquisa Produtos = F5");

        jLabel3.setText("Excluir = F7");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(55, 55, 55))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtValorBruto)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Status :");

        lblStatus.setText("jLabel3");

        lblCaixa.setText("01");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CAIXA :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Operador :");

        lblOperador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOperador.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus)
                    .addComponent(lblOperador, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblOperador))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblStatus))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Aquivos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mExcluir.add(jMenu1);

        jMenu2.setText("Comandos");

        mQuandidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mQuandidade.setText(" Quantidade F3");
        mQuandidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mQuandidadeActionPerformed(evt);
            }
        });
        jMenu2.add(mQuandidade);

        mFinalizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mFinalizarVenda.setText("Finalizar Vendas F4");
        mFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFinalizarVendaActionPerformed(evt);
            }
        });
        jMenu2.add(mFinalizarVenda);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem4.setText("Pesquisar Produtos F5");
        jMenu2.add(jMenuItem4);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem2.setText("Excluir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        mExcluir.add(jMenu2);

        setJMenuBar(mExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFinalizarVendaActionPerformed
try {
    this.viewPagamentoPdv = new ViewPagamentoPdv(this, true);
        viewPagamentoPdv.setValorTotal(Float.parseFloat(txtValorBruto.getText()));
        viewPagamentoPdv.setSubTotal();
        viewPagamentoPdv.setVisible(true);
        
      /*System.out.println(viewPagamentoPdv.getValorTotal());
        System.out.println(viewPagamentoPdv.getDesconto());
        System.out.println(viewPagamentoPdv.getFormaPagamento());
        System.out.println(viewPagamentoPdv.getTroco());*/
        
    if(viewPagamentoPdv.isPago()){
        salvarVendas();
    }else{
        JOptionPane.showMessageDialog(this, " Venda cancelo ");
    }
            
} catch (Exception e) {
    JOptionPane.showMessageDialog(this,"Você deve colocar um item na tabela ");
    
    
   }

       
       
    }//GEN-LAST:event_mFinalizarVendaActionPerformed

    private void mQuandidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mQuandidadeActionPerformed
        // TODO add your handling code here:
        quantidade = Integer.parseInt(JOptionPane.showInputDialog(" Informe a quantidade "));

    }//GEN-LAST:event_mQuandidadeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int quantidadeLinha = tblPdvVendas.getRowCount();
        if(quantidadeLinha < 1){
            JOptionPane.showMessageDialog(this, "Nenhum item na lista");
        }else{
            DefaultTableModel modelo = (DefaultTableModel)tblPdvVendas.getModel();
            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o item a ser Excluido "));
            modelo.removeRow(linha -1);
            txtValorBruto.setText(String.valueOf(somarTotal()));
            for (int i = 0; i < quantidadeLinha; i++) {
                modelo.setValueAt(i +1 , i, 0);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtCodPdvProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPdvProdutosKeyPressed
        // TODO add your handling code here: 
        carregarConteudo(evt);
    }//GEN-LAST:event_txtCodPdvProdutosKeyPressed
    //limpar a tela apos a venda
    private void limparTela(){
    txtValorBruto.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tblPdvVendas.getModel();
        modelo.setNumRows(0);
        lblStatus.setText("Caixa Livre");
    
    
    }
    
    private void carregarConteudo(java.awt.event.KeyEvent e){  
        lblStatus.setText("Venda em aberto");
        
    DefaultTableModel model = (DefaultTableModel)tblPdvVendas.getModel();
        if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER ){
            try {
            modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(txtCodPdvProdutos.getText()));
                model.addRow(new Object[]{
                    model.getRowCount()+1,
                    modelProdutos.getIdProduto(),
                    modelProdutos.getProNome(),
                    quantidade,
                    modelProdutos.getProValor(),
                    modelProdutos.getProValor() * quantidade
   
                }); 
            txtValorBruto.setText(String.valueOf(somarTotal()));
            txtCodPdvProdutos.setText("");
            quantidade = 1;      
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERRO digite um item ","Erro",JOptionPane.ERROR_MESSAGE);
                
            }

        }
        
    }
    private float somarTotal(){
    float soma = 0, valor = 0;
    int cont = tblPdvVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = Float.parseFloat(String.valueOf(tblPdvVendas.getValueAt(i, 5)));
            soma = soma + valor;
        }
    return soma;
    }
    
    private void setarOperador(){
        lblOperador.setText(modelSessaoUsuario.nome);
   
    }
    
    private void salvarVendas(){
            // TODO add your handling code here:
        int cont;
        int codigoProduto = 0, codigoVenda = 0;
       modelVendas = new ModelVenda();
       modelVendas.setCliente(1);
       
        try {
            modelVendas.setVenDateVenda(blDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewPdv.class.getName()).log(Level.SEVERE, null, ex);
        }
        //salva vendas
        modelVendas.setVenValorLiquido(blMascara.arredondamentoComPontoDuasCasasFDouble(viewPagamentoPdv.getValorTotal()));
        modelVendas.setVenValorDesconto(viewPagamentoPdv.getDesconto());
        modelVendas.setVenValorBruto(Double.parseDouble(txtValorBruto.getText()));
       
        codigoVenda = controllerVenda.salvarVendaController(modelVendas);
        
        cont = tblPdvVendas.getRowCount();
        for (int i = 0; i <cont; i++) {
            codigoProduto = (int) tblPdvVendas.getValueAt(i, 1); 
            modelVendasProdutos = new ModelVendasProdutos();
            modelProdutos = new ModelProdutos();
                // produtos vendas
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda );
                modelVendasProdutos.setVenProValor((double) tblPdvVendas.getValueAt(i, 4));
                modelVendasProdutos.setVenProQuantidade(Integer.parseInt(tblPdvVendas.getValueAt(i, 3).toString()));
                //produto
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque()
                        - Integer.parseInt(tblPdvVendas.getValueAt(i, 3).toString()));
                listaModelVendasProdutoses.add(modelVendasProdutos);
                listaModelProdutos.add(modelProdutos);
        }
       //salvar todos produtos da venda
        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)){
            controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos);
              JOptionPane.showMessageDialog(this, "Venda Produto salva com sucesso");
              limparTela();
            
        }else{
            JOptionPane.showMessageDialog(this, "ERRO ao salva Produto");
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPdv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuBar mExcluir;
    private javax.swing.JMenuItem mFinalizarVenda;
    private javax.swing.JMenuItem mQuandidade;
    private javax.swing.JTable tblPdvVendas;
    private javax.swing.JFormattedTextField txtCodPdvProdutos;
    private javax.swing.JTextField txtValorBruto;
    // End of variables declaration//GEN-END:variables
}
